version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: omnify
      POSTGRES_USER: omnify
      POSTGRES_PASSWORD: omnify
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5434"

  web:
    build: .
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn omnify.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: omnify
      DB_USER: omnify
      DB_PASSWORD: omnify
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:
